basePath: /
definitions:
  model.AddCurrencyRequest:
    properties:
      period:
        type: integer
      symbol:
        type: string
    type: object
  model.PriceResponse:
    properties:
      coin:
        type: string
      price:
        type: number
      timestamp:
        type: integer
    type: object
  model.RemoveCurrencyRequest:
    properties:
      symbol:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Микросервис для мониторинга цен криптовалют
  title: Crypto Observer API
  version: "1.0"
paths:
  /currency/add:
    post:
      consumes:
      - application/json
      description: Начать отслеживать цену криптовалюты
      parameters:
      - description: Symbol and period
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.AddCurrencyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
          schema:
            type: string
      summary: Add a cryptocurrency to watchlist
      tags:
      - currency
  /currency/price:
    get:
      consumes:
      - application/json
      description: Получить цену валюты на момент времени
      parameters:
      - description: Symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: Timestamp (unix)
        in: query
        name: timestamp
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PriceResponse'
        "404":
          description: Not found
          schema:
            type: string
      summary: Get price by symbol and timestamp
      tags:
      - currency
  /currency/remove:
    post:
      consumes:
      - application/json
      description: Прекратить отслеживать цену криптовалюты
      parameters:
      - description: Symbol
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.RemoveCurrencyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
          schema:
            type: string
      summary: Remove a cryptocurrency from watchlist
      tags:
      - currency
swagger: "2.0"
